# from github-marketplace

---
name: Python application
on:
  push:
    branches: ["main"]


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        python-version: [3.8]
    env:
      MODE: "dev"
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./Requirements.txt

      - name: Create env file
        run: |
          {
          echo MYSQL_USER=${{ secrets.mysql_user }}
          echo MYSQL_PASSWORD=${{ secrets.mysql_password }}
          echo MYSQL_DB="***REMOVED***\$database"
          echo MYSQL_HOST="127.0.0.1"
          echo MYSQL_DB_MOCK="***REMOVED***\$mockdatabase"
          echo SSH_USER="***REMOVED***"
          echo SSH_PASSWORD="***REMOVED***" 
          } >> .env

      - name: Test Code
        run: python ./test_product.py
