# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        python-version: [3.8]
    env:
      MODE: "dev"
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version}}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./Requirements.txt

    - name: Create env file
      run: |
        echo MYSQL_USER="***REMOVED***" > .env
        echo MYSQL_PASSWORD="***REMOVED***" >> .env
        echo MYSQL_DB="***REMOVED***\$database" >> .env
        echo MYSQL_HOST="127.0.0.1" >> .env
        echo MYSQL_DB_MOCK="***REMOVED***\$mockdatabase" >> .env
        echo SSH_USER="***REMOVED***" >> .env
        echo SSH_PASSWORD="***REMOVED***" >> .env

    - name: Test Code
      run: python ./test_product.py
